import { severityRank } from "./rules.js";

export function formatResult(result, format = "table") {
  if (format === "json") {
    return `${JSON.stringify(safeResult(result), null, 2)}\n`;
  }
  if (format === "markdown" || format === "md") {
    return formatMarkdown(result);
  }
  return formatTable(result);
}

export function formatTable(result) {
  const lines = [];
  const counts = result.summary.counts;

  lines.push("Agent Policy Lens");
  lines.push(`Root: ${result.root}`);
  lines.push(`Scanned files: ${result.scannedFiles.length}`);
  lines.push(`Surfaces: ${result.surfaces.length}`);
  lines.push(`Findings: ${result.summary.total} (${severityCounts(counts)})`);
  lines.push(`Highest risk: ${result.summary.highest.toUpperCase()}`);
  lines.push("");

  if (result.findings.length === 0) {
    lines.push("No risky agent permissions found.");
    return `${lines.join("\n")}\n`;
  }

  lines.push("Findings");
  result.findings.forEach((finding, index) => {
    const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
    lines.push(`${index + 1}. [${finding.severity.toUpperCase()}] ${finding.code} ${location}`);
    lines.push(`   ${finding.title}`);
    lines.push(`   Fix: ${finding.recommendation}`);
  });

  if (result.surfaces.length > 0) {
    lines.push("");
    lines.push("Agent surfaces");
    result.surfaces.forEach((surface) => {
      const pieces = [
        surface.command ? `cmd=${surface.command}` : null,
        surface.url ? `url=${surface.url}` : null,
        surface.envKeys.length ? `env=${surface.envKeys.join(",")}` : null
      ].filter(Boolean);
      lines.push(`- ${surface.name} (${surface.type}, ${surface.file})${pieces.length ? ` ${pieces.join(" ")}` : ""}`);
    });
  }

  return `${lines.join("\n")}\n`;
}

export function formatMarkdown(result) {
  const counts = result.summary.counts;
  const lines = [];

  lines.push("# Agent Policy Report");
  lines.push("");
  lines.push(`- **Root:** \`${escapeMarkdown(result.root)}\``);
  lines.push(`- **Scanned files:** ${result.scannedFiles.length}`);
  lines.push(`- **Agent surfaces:** ${result.surfaces.length}`);
  lines.push(`- **Findings:** ${result.summary.total} (${severityCounts(counts)})`);
  lines.push(`- **Highest risk:** ${result.summary.highest.toUpperCase()}`);
  lines.push("");

  if (result.findings.length === 0) {
    lines.push("No risky agent permissions found.");
    lines.push("");
  } else {
    lines.push("## Findings");
    lines.push("");
    lines.push("| Severity | Code | Location | Finding | Fix |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const finding of result.findings) {
      const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
      lines.push(`| ${badge(finding.severity)} | \`${finding.code}\` | \`${escapeMarkdown(location)}\` | ${escapeMarkdown(finding.title)} | ${escapeMarkdown(finding.recommendation)} |`);
    }
    lines.push("");
  }

  if (result.surfaces.length > 0) {
    lines.push("## Agent Surfaces");
    lines.push("");
    lines.push("| Surface | Type | File | Command / URL | Environment |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const surface of result.surfaces) {
      const commandOrUrl = surface.url ?? surface.commandLine ?? surface.command ?? "";
      lines.push(`| ${escapeMarkdown(surface.name)} | ${surface.type} | \`${escapeMarkdown(surface.file)}\` | \`${escapeMarkdown(commandOrUrl)}\` | ${surface.envKeys.map((key) => `\`${escapeMarkdown(key)}\``).join(", ") || "-"} |`);
    }
    lines.push("");
  }

  lines.push("Generated by `agent-policy-lens`.");
  lines.push("");
  return lines.join("\n");
}

export function shouldFail(summary, threshold) {
  if (!threshold || threshold === "none") {
    return false;
  }
  return severityRank[summary.highest] >= severityRank[threshold];
}

function safeResult(result) {
  return {
    ...result,
    surfaces: result.surfaces.map((surface) => ({
      id: surface.id,
      type: surface.type,
      name: surface.name,
      file: surface.file,
      command: surface.command,
      args: surface.args,
      url: surface.url,
      commandLine: surface.commandLine,
      envKeys: surface.envKeys,
      env: Object.fromEntries(Object.keys(surface.env ?? {}).map((key) => [key, "<redacted>"]))
    }))
  };
}

function severityCounts(counts) {
  return ["critical", "high", "medium", "low", "info"]
    .filter((severity) => counts[severity])
    .map((severity) => `${severity}=${counts[severity]}`)
    .join(", ") || "clean";
}

function badge(severity) {
  return severity === "critical" ? "CRITICAL"
    : severity === "high" ? "HIGH"
      : severity === "medium" ? "MEDIUM"
        : severity === "low" ? "LOW"
          : "INFO";
}

function escapeMarkdown(value) {
  return String(value ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}
